language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g grunt-cli
before_install:
- npm install npm -g
env:
  global:
  - secure: C7tci1ItBzEUztSBMjpweYPEqll2HeZnRMwLwpTA6O/Ez1P/T3IWgVwdds/z7sJi/b1yoDivzJvduy3njQSo+dcnkbg/1dkAmOYtTwYaDjym1HUABZVKAP9czvXItU5QIXws4NvyC5/5UoQ9NvPlxCliwitEC8uQONPT1Fu+k8o=
  - secure: Ma+JUWnY0l0qJ7LK9jiHRfi6SheSNIEfhBU6Yv3nz2veqNkPsltXehgrHWWxQhf1OcmV7InW82Qq9Ge2OBluDPIl6KPQcN4kfnc5pu51uCnw5RThVJ152bJXRTPFHfLiO4/lfPIqv6YcRU/f9IScYMTOsOG4bXZWjWnSIlU6vvY=
